// Script partially generated by ChatGPT

document.addEventListener('DOMContentLoaded', () => {
  // Mobile menu toggle
  const menuToggle = document.querySelector('.menu-toggle');
  const navLinks = document.querySelector('.nav-links');
  if (menuToggle) {
    menuToggle.addEventListener('click', () => {
      menuToggle.classList.toggle('active');
      navLinks.classList.toggle('active');
    });
  }

  // Remove preloader on load
  window.addEventListener('load', () => {
    gsap.to('#preloader', {
      duration: 1,
      opacity: 0,
      ease: 'power2.out',
      onComplete: () => {
        document.getElementById('preloader').style.display = 'none';
      }
    });
  });

  // Typed.js effect in hero section
  if (document.getElementById('typed')) {
    new Typed('#typed', {
      strings: ['student-athlete', 'coder', 'writer', 'designer', 'musician', 'photographer', 'kinesio-enthusiast', 'political mind', 'financial mind', 'mental health first-aider', 'student-leader'],
      typeSpeed: 120,
      backSpeed: 60,
      backDelay: 2000,
      loop: true,
      smartBackspace: true
    });
  }

  // Initial animations
  gsap.from('.main-nav', { duration: 1, y: -50, opacity: 0, ease: 'power2.out' });
  gsap.from('#hero .hero-content', { duration: 1.5, y: 50, opacity: 0, delay: 0.5, ease: 'power2.out' });

  // Scroll-triggered animations
  gsap.utils.toArray('.section').forEach(section => {
    gsap.from(section, {
      scrollTrigger: {
        trigger: section,
        start: 'top 80%',
        toggleActions: 'play none none none'
      },
      opacity: 0,
      y: 50,
      duration: 1,
      ease: 'power2.out'
    });
  });

  // Tab functionality for resume
  const tabButtons = document.querySelectorAll('.tab-button');
  const tabContents = document.querySelectorAll('.tab-content');
  if (tabButtons.length) {
    tabButtons.forEach(button => {
      button.addEventListener('click', () => {
        const targetTab = button.getAttribute('data-tab');
        tabButtons.forEach(btn => btn.classList.remove('active'));
        tabContents.forEach(content => content.classList.remove('active'));
        button.classList.add('active');
        document.getElementById(targetTab).classList.add('active');
        gsap.fromTo(`#${targetTab}`, { opacity: 0, y: 20 }, { opacity: 1, y: 0, duration: 0.5 });
      });
    });
  }

  // Contact form handler
  const contactForm = document.getElementById('contact-form');
  if (contactForm) {
    contactForm.addEventListener('submit', e => {
      e.preventDefault();
      gsap.to(contactForm, { opacity: 0.5, duration: 0.5, y: -10 });
      setTimeout(() => {
        alert('Your message has been sent!');
        gsap.to(contactForm, { opacity: 1, duration: 0.5, y: 0 });
        contactForm.reset();
      }, 1000);
    });
  }

  // Smooth scrolling for internal links
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function(e) {
      const targetId = this.getAttribute('href');
      if (targetId.length > 1) {
        e.preventDefault();
        gsap.to(window, {duration: 0.6, scrollTo: targetId, ease: 'power2.out'});
      }
    });
  });
});
